local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 40.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.25
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
